wandb_on_off: 0  # 0 for off, 1 for on
lr: 0.01
epoches: 2000
tol: 0.001
gd_strategy: "MiniBGD"   # available: "SGD" "MiniBGD"
mini_batchsize: 10
activation: "sigmoid"  # available: "sigmoid" "relu"
input_size: 1

wandb:
  project: "hw4"
  dir: "./outputs"


